(defparameter bob (init-rnn 10 60))
  (defparameter iar1 (make-array 3 :initial-contents '(.5 .5 .5)))
  (defparameter iar2 (make-array 3 :initial-contents '(.5 .5 .5)))
  (defparameter iar3 (make-array 3 :initial-contents '(.5 .5 .5)))
  (defparameter iar4 (make-array 3 :initial-contents '(.5 .5 .5)))
  (defparameter iar5 (make-array 3 :initial-contents '(.5 .5 .5)))
  (defparameter iar (make-array 5 :initial-contents (list iar1 iar2 iar3 iar4 iar5)))
  (defparameter ar1 (make-array 3 :initial-contents '(1 0 0)))
  (defparameter ar2 (make-array 3 :initial-contents '(1 0 0)))
  (defparameter ar3 (make-array 3 :initial-contents '(0 1 0)))
  (defparameter ar4 (make-array 3 :initial-contents '(0 0 1)))
  (defparameter ar5 (make-array 3 :initial-contents '(0 0 1)))
  (defparameter ar (make-array 5 :initial-contents (list ar1 ar2 ar3 ar4 ar5)))
; (generate-inputs-from-text "training_data/shakespeare.txt" 100)
(train-rnn-text "training_data/rabbit.txt" #'train-rnn-one bob .01)
