(in-package #:matlisp)

;;A helper macro which takes of care of the class checking and stuff.
(eval-every

(definline lazy-coerce (x output-type-spec)
  (if (typep x output-type-spec) x
      (let ((ret (copy x output-type-spec)))
	(when (slot-exists-p x 'memos) (iter (for (k v) in-hashtable (memos x)) (setf (gethash k (memos ret)) v)))
	ret)))

(defun real-subtypep (type) (match type ((lambda-list 'cl:complex &optional (type t)) type)))
(defun cclass-max (&rest lst)
  (iter (for ele in lst) (with max)
	(when (or (null max)
		  (and (coerceable? max ele)
		       (or (not (coerceable? ele max))
			   (and (float-tensorp ele) (float-tensorp max)
				(> (float-digits (coerce 0 (or (real-subtypep (field-type ele)) (field-type ele))))
				   (float-digits (coerce 0 (or (real-subtypep (field-type max)) (field-type max)))))))))
	  (setf max ele))
	(finally (return max))))
;;(cclass-max (tensor '(complex double-float)) (tensor '(complex double-float)))

;;MOP layer to fix issues with generation and subclassing.
(closer-mop:defclass tensor-method-generator (closer-mop:standard-generic-function) ()
  (:metaclass closer-mop:funcallable-standard-class))
;;Specializers
(closer-mop:defclass classp-specializer (closer-mop:specializer)
  ((object-class :initform nil :initarg :object-class)
   (direct-methods :initform nil :reader closer-mop:specializer-direct-methods))
  (:documentation "Exact class specializer."))
(closer-mop:defmethod print-object ((obj classp-specializer) stream)
  (print-unreadable-object (obj stream :type t)
    (format stream ", ~a" (class-name (slot-value obj 'object-class)))))

(closer-mop:defmethod closer-mop:add-direct-method ((specializer classp-specializer) method)
  (pushnew method (slot-value specializer 'direct-methods)))
(closer-mop:defmethod closer-mop:remove-direct-method ((specializer classp-specializer) method)
  (setf (slot-value specializer 'direct-methods)
	(remove method (slot-value specializer 'direct-methods))))
(closer-mop:defmethod make-load-form ((obj classp-specializer) &optional env)
  #+nil(make-load-form-saving-slots obj :environment env)
  (values `(classp-specializer ',(class-name (slot-value obj 'object-class))) nil))
;;
(closer-mop:defclass group-specializer (closer-mop:specializer)
  ((object-class :initform nil :initarg :object-class)
   (group-name :initform nil :initarg :group-name)
   (direct-methods :initform nil :reader closer-mop:specializer-direct-methods))
  (:documentation "Applicable only if for each group-specializer with distinct @argument{group-name}, the classes of the respective argument are the same."))
(closer-mop:defmethod print-object ((obj group-specializer) stream)
  (print-unreadable-object (obj stream :type t)
    (format stream ", ~a, ~a" (class-name (slot-value obj 'object-class)) (slot-value obj 'group-name))))

(closer-mop:defmethod closer-mop:add-direct-method ((specializer group-specializer) method)
  (pushnew method (slot-value specializer 'direct-methods)))
(closer-mop:defmethod closer-mop:remove-direct-method ((specializer group-specializer) method)
  (setf (slot-value specializer 'direct-methods)
	(remove method (slot-value specializer 'direct-methods))))
(closer-mop:defmethod make-load-form ((obj group-specializer) &optional env)
  #+nil(make-load-form-saving-slots obj :environment env)
  (values `(group-specializer ',(class-name (slot-value obj 'object-class)) ',(slot-value obj 'group-name)) nil))
;;Subtype
(closer-mop:defclass subtype-specializer (closer-mop:specializer)
  ((specializer-type :initform nil :initarg :specializer-type)
   (direct-methods :initform nil :reader closer-mop:specializer-direct-methods))
  (:documentation "Applicable only if for each group-specializer with distinct @argument{group-name}, the classes of the respective argument are the same."))
(closer-mop:defmethod print-object ((obj subtype-specializer) stream)
  (print-unreadable-object (obj stream :type t)
    (format stream ", ~a" (slot-value obj 'specializer-type))))

(closer-mop:defmethod closer-mop:add-direct-method ((specializer subtype-specializer) method)
  (pushnew method (slot-value specializer 'direct-methods)))
(closer-mop:defmethod closer-mop:remove-direct-method ((specializer subtype-specializer) method)
  (setf (slot-value specializer 'direct-methods)
	(remove method (slot-value specializer 'direct-methods))))
(closer-mop:defmethod make-load-form ((obj subtype-specializer) &optional env)
  #+nil(make-load-form-saving-slots obj :environment env)
  (values `(subtype-specializer ',(slot-value obj 'specializer-type)) nil))
;;
(defparameter *specializer-table* (make-hash-table :test 'equal))
(with-memoization (*specializer-table*)
  (memoizing
   (defun classp-specializer (class-name)
     (make-instance 'classp-specializer :object-class (find-class class-name))))
  (memoizing
   (defun group-specializer (class-name group-name)
     (make-instance 'group-specializer :object-class (find-class class-name) :group-name (the keyword group-name))))
  (memoizing
   (defun subtype-specializer (specializer-type)
     (make-instance 'subtype-specializer :specializer-type specializer-type))))

;;
(closer-mop:defmethod closer-mop:compute-applicable-methods-using-classes ((gf tensor-method-generator) required-classes)
  (iter mc
	(for m in (closer-mop:generic-function-methods gf))
	(with class-info-enoughp = t)
	(iter (for s in (closer-mop:method-specializers m))
	      (for c in required-classes) (with group-keys = nil)
	      (always
	       (etypecase s
		 (class (subtypep c s))
		 (closer-mop:eql-specializer (and (eql c (class-of (closer-mop:eql-specializer-object s)))
						  (not (setf class-info-enoughp nil))))
		 (subtype-specializer (and (or (eql c (find-class 'symbol)) (eql c (find-class 'list)))
					   (not (setf class-info-enoughp nil))))
		 (group-specializer
		  (let ((key-name (slot-value s 'group-name)))
		    (if-let ((key (assoc key-name group-keys)))
		      (eql (cdr key) c)
		      (when (subtypep c (slot-value s 'object-class))
			(push (cons key-name c) group-keys) t))))
		 (classp-specializer (eq c (slot-value s 'object-class)))))
	      (finally (in mc (collect m into applicable-methods))))
	(finally (return-from mc
		   (values (sort (copy-list applicable-methods) #'(lambda (m1 m2) (method-more-specific-p m1 m2 required-classes)))
			   class-info-enoughp)))))

(closer-mop:defmethod compute-applicable-methods ((gf tensor-method-generator) arguments &aux (argument-classes (mapcar #'class-of arguments)))
  (iter mc
	(for m in (closer-mop:generic-function-methods gf))
	(iter (for s in (closer-mop:method-specializers m))
	      (for a in arguments) (with group-keys = nil)
	      (always
	       (etypecase s
		 (class (typep a s))
		 (closer-mop:eql-specializer (and (eql a (closer-mop:eql-specializer-object s))))
		 (subtype-specializer (subtypep a (slot-value s 'specializer-type)))
		 (group-specializer
		  (let ((key-name (slot-value s 'group-name)))
		    (if-let ((key (assoc key-name group-keys)))
		      (eql (cdr key) (class-of a))
		      (when (typep a (slot-value s 'object-class))
			(push (cons key-name (class-of a)) group-keys) t))))
		 (classp-specializer (eq (class-of a) (slot-value s 'object-class)))))
	      (finally (in mc (collect m into applicable-methods))))
	(finally (return-from mc (sort (copy-list applicable-methods) #'(lambda (m1 m2) (method-more-specific-p m1 m2 argument-classes)))))))

;;Add closer-mop:compute-applicable-methods
;;Borrowed from AMOP p.122
(defun method-more-specific-p (method1 method2 required-classes)
  (map nil #'(lambda (spec1 spec2 arg-class)
	       (unless (or (eq spec1 spec2)
			   (cart-typecase (spec1 spec2)
			     ((classp-specializer classp-specializer) (eq (slot-value spec1 'object-class) (slot-value spec1 'object-class)))
			     ((group-specializer group-specializer) (and (eq (slot-value spec1 'object-class) (slot-value spec1 'object-class))
									 (eq (slot-value spec1 'group-name) (slot-value spec1 'group-name))))
			     ((subtype-specializer subtype-specializer) (and (eq (slot-value spec1 'specializer-type) (slot-value spec2 'specializer-type))))))
		 (return-from method-more-specific-p (sub-specializer-p spec1 spec2 arg-class))))
       (closer-mop:method-specializers method1)
       (closer-mop:method-specializers method2)
       required-classes))

(defun sub-specializer-p (spec1 spec2 arg-class)
  (cart-typecase (spec1 spec2)
    ((class class) (not (null (find spec2 (cdr (member spec1 (closer-mop:class-precedence-list arg-class)))))))
    ((classp-specializer classp-specializer) (sub-specializer-p (the class (slot-value spec1 'object-class)) (the class (slot-value spec2 'object-class)) arg-class))
    ;;classp-specializer in list if spec1.object-class = arg-class
    ((classp-specializer class) t)
    ((group-specializer class)
     (if (or (eq (slot-value spec1 'object-class) spec2)
	     (sub-specializer-p (slot-value spec1 'object-class) spec2 arg-class))
	 t nil))
    ((class group-specializer) (sub-specializer-p spec1 (slot-value spec2 'object-class) arg-class))
    ((classp-specializer group-specializer)
     (or (eq (slot-value spec1 'object-class) (slot-value spec2 'object-class))
	 (sub-specializer-p (slot-value spec1 'object-class) (slot-value spec2 'object-class) arg-class)))
    ((group-specializer classp-specializer)
     (sub-specializer-p (slot-value spec1 'object-class) (slot-value spec2 'object-class) arg-class))
    ((subtype-specializer (or group-specializer classp-specializer class)) t)
    ((subtype-specializer subtype-specializer) (subtypep (slot-value spec1 'specializer-type) (slot-value spec2 'specializer-type)))
    ((closer-mop:eql-specializer t) t)))

(defparameter *template-generated-methods* (make-hash-table :test 'equal))
;;(closer-mop:subclassp (find-class (tensor 'double-float)) (find-class 'base-tensor))
(defmacro define-tensor-method (name (&rest args) &body body)
  (let* ((keypos (or (position-if (lambda (x) (member x cl:lambda-list-keywords)) args) (length args)))
	 (dispatch-args (subseq args 0 keypos))
	 (dispatch-key (mapcar (lambda (x) (if (consp x) (second x) t)) dispatch-args))
	 (generate-args (remove-if-not #'(lambda (x) (and (consp x) (cddr x))) dispatch-args))
	 (generate-groups (iter (for ele in generate-args) (unioning (list (third ele))))))
    (with-gensyms (xx value existsp type-methods func)
      `(eval-every
	 ;;clear methods
	 (letv* ((,value ,existsp (gethash ',name *template-generated-methods*)))
	   (if ,existsp
	       (if-let ((,type-methods (assoc ',dispatch-key (cdr ,value) :test #'equal)))
		 (iter (for ,func in (cdr ,type-methods))
		       (remove-method (function ,name) ,func)
		       (finally (setf (cdr ,type-methods) nil)))
		 (setf (cdr ,value) (list* (list ',dispatch-key) (cdr ,value))))
	       (setf (gethash ',name *template-generated-methods*) (list ',name (list ',dispatch-key)))))
	 ;;generic type coercer.
	 ,@(let* ((coerce-groups (remove-if-not #'(lambda (x) (< 1 (length (remove-if-not #'(lambda (y) (eql x (third y))) generate-args)))) generate-groups))
		  (sym (zipsym coerce-groups)))
	     (when coerce-groups
	       `((closer-mop:defmethod ,name (,@(mapcar #'(lambda (x) (if (consp x) (subseq x 0 2) x)) (subseq args 0 keypos)) ,@(subseq args keypos))
		   (let (,@(iter (for (ts g) in sym)
				 (collect `(,ts ,(rec c+ ((lst (remove-if-not #'(lambda (x) (eql g (third x))) generate-args)))
						      (when lst `(cclass-max (type-of ,(first (car lst))) ,(c+ (cdr lst)))))))))
		     ,@(iter (for (ts g) in sym)
			     (appending (mapcar #'(lambda (x)
						    `(assert (eql ,ts (type-of ,(first x))) nil "output type clash: don't know how to generate code for the given arguments."))
						(remove-if-not #'(lambda (x) (and (eql g (third x)) (fourth x))) generate-args))))
		     ,@(let ((dargs (mapcar #'(lambda (x)
						(match x
						  ((lambda-list name _ group &optional destructive)
						   (if (or destructive (not (member group coerce-groups))) name `(lazy-coerce ,name ,(first (rassoc (list group) sym :test #'equal)))))
						  ((list name _) name)
						  (_ x)))
					    (subseq args 0 keypos))))
			    (if-let ((rest-pos (position '&rest args)))
			      `((apply #',name (list* ,@dargs ,@(mapcar #'(lambda (x) (first (ensure-list x))) (set-difference (subseq args keypos rest-pos) cl:lambda-list-keywords))
						      ,(elt args (1+ rest-pos)))))
			      `((,@(if (symbolp name) `(,name) `(funcall #',name)) ,@dargs ,@(mapcar #'(lambda (x) (first (ensure-list x))) (set-difference (subseq args keypos) cl:lambda-list-keywords)))))))))))
	 ;;method generator.
	 ,@(let ((sym (zipsym generate-groups)))
	     `((closer-mop:defmethod ,name (,@(mapcar (lambda (x) (match x
							 ((lambda-list name dispatch group &optional _)
							  `(,name ,(group-specializer dispatch group)))
							 (_ x)))
					   (subseq args 0 keypos))
				 ,@(subseq args keypos))
		 (let (,@(iter (for (tg g) in sym) (collect `(,tg (type-of ,(first (find-if #'(lambda (x) (eql (third x) g)) generate-args))))))
		       (,xx (or (assoc ',dispatch-key (cdr (gethash ',name *template-generated-methods*)) :test #'equal)
				(error "Method table missing from *template-generated-methods*!"))))
		   ;;(format t "Compiling ~a method for dispatch ~s." ',name ,coerce-types)
		   (push
		    (macrolet ((cl (,xx) (ecase ,xx ,@(mapcar #'(lambda (x) `(,(second x) (quote ,(first x))))  sym))))
		      (compile-and-eval
		       `(closer-mop:defmethod ,',name (,@(list ,@(mapcar (lambda (x) (match x
									    ((lambda-list name _ group &optional _)
									     `(list ',name (classp-specializer (cl ,group))))
									    (_ `(quote ,x))))
							      (subseq args 0 keypos)))
													  ,@',(subseq args keypos))
			  ,@(list ,@body))))
		    (cdr ,xx)))
		 ,@(let ((dargs (mapcar #'(lambda (x) (first (ensure-list x))) (subseq args 0 keypos))))
			(if-let ((rest-pos (position '&rest args)))
			  `((apply #',name (list* ,@dargs ,@(mapcar #'(lambda (x) (first (ensure-list x))) (set-difference (subseq args keypos rest-pos) cl:lambda-list-keywords))
						  ,(elt args (1+ rest-pos)))))
			  `((,@(if (symbolp name) `(,name) `(funcall #',name)) ,@dargs ,@(mapcar #'(lambda (x) (first (ensure-list x))) (remove-if #'(lambda (x) (member x cl:lambda-list-keywords)) (subseq args keypos))))))))))))))
)
